name: Visual Studio C++ Build (Static)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH (x64)
        if: matrix.platform == 'x64'
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Add MSBuild to PATH (Win32)
        if: matrix.platform == 'Win32'
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86

      - name: Build Solution
        run: msbuild StopSaver.sln /p:Configuration=Release /p:Platform=${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-application-${{ matrix.platform }}
          path: StopSaver\Release\StopSaver.exe
